name: 🐞 报告错误
description: 报告一个错误（Bug），请先查看常见问题、置顶说明、及搜索本仓库及原仓库 Issue 列表中有无你要提的问题。
title: '[Bug]: '
body:
  - type: checkboxes
    id: check-answer
    attributes:
      label: 解决方案检查
      description: 请确保你已完成以下所有操作
      options:
        - label: 我已阅读 [常见问题](https://lyswhut.github.io/lx-music-doc/mobile/faq)，但没有找到解决方案。
          required: true
        - label: 我已搜索 [本仓库Issue 列表](https://github.com/souvenp/lx-netease-music-mobile/issues?q=is%3Aissue+) 和 [原仓库Issue 列表](https://github.com/lyswhut/lx-music-mobile/issues)，但没有发现类似的问题。
          required: true
        - label: 我已阅读 [说明](https://github.com/souvenp/lx-netease-music-mobile/issues/50)。
          required: true
        - label: 我已浏览了全部设置，并尝试调整相关选项，但问题仍然存在。
          required: true
        - label: 我确认我正在使用的是最新版本的 App。
          required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 对期望发生的事情的清晰详细描述，不具体说明无法处理。
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 对实际发生的事情的清晰详细描述，必要时附上截图，不具体说明无法处理。
    validations:
      required: true
  - type: input
    id: last-known-working-version
    attributes:
      label: 最后正常的版本
      description: 如果有，请在此处填写最后正常的版本。
      placeholder: 1.5.0 arm64-v8a
  - type: input
    id: operating-system-version
    attributes:
      label: 操作系统版本
      description: |
        你使用什么版本的操作系统？
        在 Android 上，通常单击「系统设置 > 关于」。
        各类厂商定制 Android 系统的位置可能有所不同。
      placeholder: 例如 Android 15
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: 附加信息
      description: 如果你的问题需要进一步解释，或者你所遇到的问题不容易重现，请在此处添加更多信息。（直接把图片/视频拖到编辑框即可添加图片/视频）
